/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisuelRouteImport } from './routes/visuel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as PlatformerRouteImport } from './routes/platformer'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MiamsRouteImport } from './routes/miams'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScamWinnerOmgLegacyRouteImport } from './routes/scamWinnerOmg.legacy'
import { Route as GamesGalakiRouteImport } from './routes/games.galaki'
import { Route as AdminRightsRouteImport } from './routes/admin.rights'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCreateUserRouteImport } from './routes/admin.createUser'
import { Route as ScamWinnerOmgRouteImport } from './routes/scam.winner.omg'

const VisuelRoute = VisuelRouteImport.update({
  id: '/visuel',
  path: '/visuel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformerRoute = PlatformerRouteImport.update({
  id: '/platformer',
  path: '/platformer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MiamsRoute = MiamsRouteImport.update({
  id: '/miams',
  path: '/miams',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamWinnerOmgLegacyRoute = ScamWinnerOmgLegacyRouteImport.update({
  id: '/scamWinnerOmg/legacy',
  path: '/scamWinnerOmg/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGalakiRoute = GamesGalakiRouteImport.update({
  id: '/games/galaki',
  path: '/games/galaki',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRightsRoute = AdminRightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/createUser',
  path: '/createUser',
  getParentRoute: () => AdminRoute,
} as any)
const ScamWinnerOmgRoute = ScamWinnerOmgRouteImport.update({
  id: '/scam/winner/omg',
  path: '/scam/winner/omg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/miams': typeof MiamsRoute
  '/planning': typeof PlanningRoute
  '/platformer': typeof PlatformerRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/visuel': typeof VisuelRoute
  '/admin/createUser': typeof AdminCreateUserRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rights': typeof AdminRightsRoute
  '/games/galaki': typeof GamesGalakiRoute
  '/scamWinnerOmg/legacy': typeof ScamWinnerOmgLegacyRoute
  '/scam/winner/omg': typeof ScamWinnerOmgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/miams': typeof MiamsRoute
  '/planning': typeof PlanningRoute
  '/platformer': typeof PlatformerRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/visuel': typeof VisuelRoute
  '/admin/createUser': typeof AdminCreateUserRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rights': typeof AdminRightsRoute
  '/games/galaki': typeof GamesGalakiRoute
  '/scamWinnerOmg/legacy': typeof ScamWinnerOmgLegacyRoute
  '/scam/winner/omg': typeof ScamWinnerOmgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/miams': typeof MiamsRoute
  '/planning': typeof PlanningRoute
  '/platformer': typeof PlatformerRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/visuel': typeof VisuelRoute
  '/admin/createUser': typeof AdminCreateUserRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rights': typeof AdminRightsRoute
  '/games/galaki': typeof GamesGalakiRoute
  '/scamWinnerOmg/legacy': typeof ScamWinnerOmgLegacyRoute
  '/scam/winner/omg': typeof ScamWinnerOmgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ideas'
    | '/login'
    | '/miams'
    | '/planning'
    | '/platformer'
    | '/scheduler'
    | '/settings'
    | '/visuel'
    | '/admin/createUser'
    | '/admin/notifications'
    | '/admin/rights'
    | '/games/galaki'
    | '/scamWinnerOmg/legacy'
    | '/scam/winner/omg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ideas'
    | '/login'
    | '/miams'
    | '/planning'
    | '/platformer'
    | '/scheduler'
    | '/settings'
    | '/visuel'
    | '/admin/createUser'
    | '/admin/notifications'
    | '/admin/rights'
    | '/games/galaki'
    | '/scamWinnerOmg/legacy'
    | '/scam/winner/omg'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ideas'
    | '/login'
    | '/miams'
    | '/planning'
    | '/platformer'
    | '/scheduler'
    | '/settings'
    | '/visuel'
    | '/admin/createUser'
    | '/admin/notifications'
    | '/admin/rights'
    | '/games/galaki'
    | '/scamWinnerOmg/legacy'
    | '/scam/winner/omg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  IdeasRoute: typeof IdeasRoute
  LoginRoute: typeof LoginRoute
  MiamsRoute: typeof MiamsRoute
  PlanningRoute: typeof PlanningRoute
  PlatformerRoute: typeof PlatformerRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
  VisuelRoute: typeof VisuelRoute
  GamesGalakiRoute: typeof GamesGalakiRoute
  ScamWinnerOmgLegacyRoute: typeof ScamWinnerOmgLegacyRoute
  ScamWinnerOmgRoute: typeof ScamWinnerOmgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visuel': {
      id: '/visuel'
      path: '/visuel'
      fullPath: '/visuel'
      preLoaderRoute: typeof VisuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platformer': {
      id: '/platformer'
      path: '/platformer'
      fullPath: '/platformer'
      preLoaderRoute: typeof PlatformerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miams': {
      id: '/miams'
      path: '/miams'
      fullPath: '/miams'
      preLoaderRoute: typeof MiamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scamWinnerOmg/legacy': {
      id: '/scamWinnerOmg/legacy'
      path: '/scamWinnerOmg/legacy'
      fullPath: '/scamWinnerOmg/legacy'
      preLoaderRoute: typeof ScamWinnerOmgLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/galaki': {
      id: '/games/galaki'
      path: '/games/galaki'
      fullPath: '/games/galaki'
      preLoaderRoute: typeof GamesGalakiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rights': {
      id: '/admin/rights'
      path: '/rights'
      fullPath: '/admin/rights'
      preLoaderRoute: typeof AdminRightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/createUser': {
      id: '/admin/createUser'
      path: '/createUser'
      fullPath: '/admin/createUser'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scam/winner/omg': {
      id: '/scam/winner/omg'
      path: '/scam/winner/omg'
      fullPath: '/scam/winner/omg'
      preLoaderRoute: typeof ScamWinnerOmgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRightsRoute: typeof AdminRightsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateUserRoute: AdminCreateUserRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRightsRoute: AdminRightsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  IdeasRoute: IdeasRoute,
  LoginRoute: LoginRoute,
  MiamsRoute: MiamsRoute,
  PlanningRoute: PlanningRoute,
  PlatformerRoute: PlatformerRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
  VisuelRoute: VisuelRoute,
  GamesGalakiRoute: GamesGalakiRoute,
  ScamWinnerOmgLegacyRoute: ScamWinnerOmgLegacyRoute,
  ScamWinnerOmgRoute: ScamWinnerOmgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
